# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import log_pb2 as log__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in log_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UploadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadLogs = channel.unary_unary(
                '/terraformlogviewer.UploadService/UploadLogs',
                request_serializer=log__pb2.UploadLogsRequest.SerializeToString,
                response_deserializer=log__pb2.UploadLogsResponse.FromString,
                _registered_method=True)


class UploadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadLogs,
                    request_deserializer=log__pb2.UploadLogsRequest.FromString,
                    response_serializer=log__pb2.UploadLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terraformlogviewer.UploadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terraformlogviewer.UploadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UploadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terraformlogviewer.UploadService/UploadLogs',
            log__pb2.UploadLogsRequest.SerializeToString,
            log__pb2.UploadLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LogParserServiceStub(object):
    """Интерфейс сервиса парсинга
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseLogs = channel.unary_unary(
                '/terraformlogviewer.LogParserService/ParseLogs',
                request_serializer=log__pb2.ParseLogsRequest.SerializeToString,
                response_deserializer=log__pb2.ParseLogsResponse.FromString,
                _registered_method=True)


class LogParserServiceServicer(object):
    """Интерфейс сервиса парсинга
    """

    def ParseLogs(self, request, context):
        """Парсинг пачки логов с возвратом структурированных записей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseLogs,
                    request_deserializer=log__pb2.ParseLogsRequest.FromString,
                    response_serializer=log__pb2.ParseLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terraformlogviewer.LogParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terraformlogviewer.LogParserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogParserService(object):
    """Интерфейс сервиса парсинга
    """

    @staticmethod
    def ParseLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terraformlogviewer.LogParserService/ParseLogs',
            log__pb2.ParseLogsRequest.SerializeToString,
            log__pb2.ParseLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
