# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x12terraformlogviewer\"\"\n\x10ParseLogsRequest\x12\x0e\n\x06log_id\x18\x01 \x01(\t\"\xae\x01\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07section\x18\x03 \x01(\t\x12\x11\n\ttf_req_id\x18\x04 \x01(\t\x12\x18\n\x10tf_resource_type\x18\x05 \x01(\t\x12\x0b\n\x03raw\x18\x06 \x01(\t\x12\x19\n\x11request_body_json\x18\x07 \x01(\t\x12\x1a\n\x12response_body_json\x18\x08 \x01(\t\"B\n\x11ParseLogsResponse\x12-\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1c.terraformlogviewer.LogEntry\"6\n\x11UploadLogsRequest\x12\x10\n\x08log_file\x18\x01 \x01(\x0c\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"$\n\x12UploadLogsResponse\x12\x0e\n\x06log_id\x18\x01 \x01(\t2n\n\rUploadService\x12]\n\nUploadLogs\x12%.terraformlogviewer.UploadLogsRequest\x1a&.terraformlogviewer.UploadLogsResponse\"\x00\x32n\n\x10LogParserService\x12Z\n\tParseLogs\x12$.terraformlogviewer.ParseLogsRequest\x1a%.terraformlogviewer.ParseLogsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSELOGSREQUEST']._serialized_start=33
  _globals['_PARSELOGSREQUEST']._serialized_end=67
  _globals['_LOGENTRY']._serialized_start=70
  _globals['_LOGENTRY']._serialized_end=244
  _globals['_PARSELOGSRESPONSE']._serialized_start=246
  _globals['_PARSELOGSRESPONSE']._serialized_end=312
  _globals['_UPLOADLOGSREQUEST']._serialized_start=314
  _globals['_UPLOADLOGSREQUEST']._serialized_end=368
  _globals['_UPLOADLOGSRESPONSE']._serialized_start=370
  _globals['_UPLOADLOGSRESPONSE']._serialized_end=406
  _globals['_UPLOADSERVICE']._serialized_start=408
  _globals['_UPLOADSERVICE']._serialized_end=518
  _globals['_LOGPARSERSERVICE']._serialized_start=520
  _globals['_LOGPARSERSERVICE']._serialized_end=630
# @@protoc_insertion_point(module_scope)
