"""bug fix

Revision ID: a968f2bc73fa
Revises: 49caee5b681f
Create Date: 2025-10-02 11:35:00.524198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a968f2bc73fa'
down_revision: Union[str, Sequence[str], None] = '49caee5b681f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_lines', 'section',
               existing_type=postgresql.ENUM('PLAN', 'APPLY', name='logsection'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_lines', 'section',
               existing_type=postgresql.ENUM('PLAN', 'APPLY', name='logsection'),
               nullable=False)
    # ### end Alembic commands ###
