"""bug fix

Revision ID: 49caee5b681f
Revises: d6c900d1280e
Create Date: 2025-10-02 11:33:33.020350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49caee5b681f'
down_revision: Union[str, Sequence[str], None] = 'd6c900d1280e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_lines', 'level',
               existing_type=postgresql.ENUM('INFO', 'WARN', 'ERROR', 'WARNING', 'DEBUG', 'TRACE', name='loglevel'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_lines', 'level',
               existing_type=sa.String(),
               type_=postgresql.ENUM('INFO', 'WARN', 'ERROR', 'WARNING', 'DEBUG', 'TRACE', name='loglevel'),
               existing_nullable=False)
    # ### end Alembic commands ###
