"""bug fix

Revision ID: d6c900d1280e
Revises: a38330301f55
Create Date: 2025-10-02 11:20:18.186569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c900d1280e'
down_revision: Union[str, Sequence[str], None] = 'a38330301f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARN', 'ERROR', 'WARNING', 'DEBUG', 'TRACE', name='loglevel'), nullable=False),
    sa.Column('section', sa.Enum('PLAN', 'APPLY', name='logsection'), nullable=False),
    sa.Column('tf_req_id', sa.String(), nullable=True),
    sa.Column('request_body', sa.String(), nullable=True),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('raw', sa.String(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('logs', 'log_analistics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('log_analistics', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('log_lines')
    # ### end Alembic commands ###
